apiVersion: apps/v1 # bucket for Deployment kind
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1 # number of pods running a particular image
  selector: # take a look at all the pods created
    matchLabels: # find the pods with a matching label
      app: comments # match only pods with label of "app: comments"
  template: # specify the exact configuration to be deployed
    metadata:
      labels: # the configuration will create a label
        app: comments # with the value of "app: comments"
    spec:
      containers: # specify the containers to be deployed
        - name: comments
          image: acxmatos/comments
---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  selector:
    app: comments
  type: ClusterIP # default if not specified
  ports:
    - name: comments
      protocol: TCP
      port: 4001
      targetPort: 4001