apiVersion: apps/v1 # bucket for Deployment kind
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1 # number of pods running a particular image
  selector: # take a look at all the pods created
    matchLabels: # find the pods with a matching label
      app: event-bus # match only pods with label of "app: event-bus"
  template: # specify the exact configuration to be deployed
    metadata:
      labels: # the configuration will create a label
        app: event-bus # with the value of "app: event-bus"
    spec:
      containers: # specify the containers to be deployed
        - name: event-bus
          image: acxmatos/event-bus
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  selector:
    app: event-bus
  type: ClusterIP # default if not specified
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005
      targetPort: 4005