apiVersion: apps/v1 # bucket for Deployment kind
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1 # number of pods running a particular image
  selector: # take a look at all the pods created
    matchLabels: # find the pods with a matching label
      app: posts # match only pods with label of "app: posts"
  template: # specify the exact configuration to be deployed
    metadata:
      labels: # the configuration will create a label
        app: posts # with the value of "app: posts"
    spec:
      containers: # specify the containers to be deployed
        - name: posts
          image: acxmatos/posts
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  type: ClusterIP # default if not specified
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000